import { chromium } from 'playwright';
const OUT = process.env.OUT;
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1400, height: 900 }, colorScheme: 'dark' });
p.on('dialog', (d) => d.accept());
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://127.0.0.1:3838/');
await p.fill('input[name=username]', process.env.MDNEST_USER); await p.fill('input[name=password]', process.env.MDNEST_PASSWORD);
await p.click('button:has-text("Sign in")'); await p.waitForSelector('.ns-label, .ns-select');
await p.click('.sidebar-user-row'); await p.click('.user-menu-item:has-text("Manage Users")');
await p.waitForSelector('[data-testid=adm-person]');
await p.screenshot({ path: `${OUT}/adm-people.png` });
const uname = `e2eadm${Date.now() % 100000}`;
await p.getByTestId('adm-invite-toggle').click();
await p.fill('[data-testid=adm-invite] input[type=email]', `${uname}@example.test`);
await p.fill('[data-testid=adm-invite] input[placeholder=Username]', uname);
await p.fill('[data-testid=adm-invite] input[type=password]', 'TempPass-12345');
const grp = p.locator('[data-testid=adm-invite] .adm-chip-pick', { hasText: 'qa-team' });
if (await grp.count()) await grp.click();
await p.screenshot({ path: `${OUT}/adm-invite.png` });
await p.click('[data-testid=adm-invite] button[type=submit]');
const card = p.locator('[data-testid=adm-person]', { hasText: uname });
await card.locator('[data-testid=adm-reach], .adm-sec').first().waitFor({ timeout: 10000 });
await p.waitForTimeout(800);
await card.screenshot({ path: `${OUT}/adm-person-open.png` });
console.log('reach:', await card.locator('.adm-sec').last().innerText().catch(() => ''));
await p.click('.admin-tabs button:has-text("Namespaces")');
const nsCard = p.locator('[data-testid=adm-namespace]').first(); await nsCard.locator('.grants-user-header').click();
await p.waitForTimeout(500);
await p.screenshot({ path: `${OUT}/adm-ns.png`, fullPage: true });
const id = await p.evaluate(async (u) => { const h = { Authorization: 'Bearer ' + localStorage.getItem('mdnest_token') }; const us = await (await fetch('/api/admin/users', { headers: h })).json(); const x = us.find((y) => y.username === u); if (x) await fetch(`/api/admin/users?id=${x.id}`, { method: 'DELETE', headers: h }); return x?.id; }, uname);
console.log('cleaned', id, 'errors', errs);
await b.close();
